services:
  app:
    image: sungaibudiwebdev/tebu-app:latest
    container_name: tebu-app
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./storage:/var/www/html/storage
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./docker/nginx/default.conf:/etc/nginx/http.d/default.conf:ro
    networks:
      - tebu-network

  redis:
    image: redis:7-alpine
    container_name: tebu-redis
    restart: unless-stopped
    networks:
      - tebu-network

networks:
  tebu-network:
    external: true