name: Deploy Tebu Apps (LINUX SSM)

# Memicu manual dari tab Actions di GitHub
on:
  workflow_dispatch: {} 

jobs:
  # --- TAHAP 1: BUILD IMAGE ---
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Menggunakan tag latest agar selalu terupdate
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tebu-app:latest

  # --- TAHAP 2: DEPLOY KE AWS ---
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Prepare and Send SSM command
        id: send
        run: |
          # 1. Ubah file docker-compose.yml jadi satu baris kode rahasia (Base64)
          B64_COMPOSE=$(base64 -w 0 docker-compose.yml)

          # 2. Kirim perintah ke AWS
          CMD_ID=$(aws ssm send-command \
            --region "${{ secrets.AWS_REGION }}" \
            --document-name "AWS-RunShellScript" \
            --instance-ids "${{ secrets.SSM_INSTANCE_ID_LINUX }}" \
            --parameters "commands=[
              \"mkdir -p /opt/apps/tebu\",
              \"cd /opt/apps/tebu\",
              # Decode kembali file base64 tadi menjadi file .yml asli
              \"echo $B64_COMPOSE | base64 -d > docker-compose.yml\",
              \"sudo docker compose pull\",
              \"sudo docker compose up -d\"
            ]" \
            --query "Command.CommandId" \
            --output text)
          
          echo "command_id=$CMD_ID" >> "$GITHUB_OUTPUT"
          echo "SSM Command sent with ID: $CMD_ID"

      - name: Check Deployment Result
        run: |
          CMD_ID="${{ steps.send.outputs.command_id }}"
          INSTANCE_ID="${{ secrets.SSM_INSTANCE_ID_LINUX }}"
          
          # Tunggu sebentar agar server sempat memproses
          sleep 15
          
          aws ssm get-command-invocation \
            --command-id "$CMD_ID" \
            --instance-id "$INSTANCE_ID" \
            --query "{Status:Status,Output:StandardOutputContent,Error:StandardErrorContent}" \
            --output json